
export const arab_countries = [
    { name: "Algeria", code: "DZ" },
    { name: "Bahrain", code: "BH" },
    { name: "Egypt", code: "EG" },
    { name: "Iraq", code: "IQ" },
    { name: "Jordan", code: "JO" },
    { name: "Kuwait", code: "KW" },
    { name: "Lebanon", code: "LB" },
    { name: "Libya", code: "LY" },
    { name: "Morocco", code: "MA" },
    { name: "Oman", code: "OM" },
    { name: "Palestine", code: "PS" },
    { name: "Qatar", code: "QA" },
    { name: "Saudi Arabia", code: "SA" },
    { name: "Syria", code: "SY" },
    { name: "Tunisia", code: "TN" },
    { name: "United Arab Emirates", code: "AE" },
    { name: "Yemen", code: "YE" },
];