import {Geist, Inter} from "next/font/google";
import "./globals.css";
import {Toaster} from "react-hot-toast";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html
      lang="en"
      className={`${geist.variable} ${inter.variable} h-full antialiased dark`}>
      <body className="min-h-full flex flex-col">
        <div>{children}</div>

        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
